services:
    AustinMaddox.tencentcos.listener:
        class: AustinMaddox\tencentcos\event\main_listener
        arguments:
            - @config
            - @template
            - @user
            - @log
            - %core.root_path%
        tags:
            - { name: event.listener }
